name: Terraform Plan

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform authenticated plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials through OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::290909957115:role/github-actions-terraform-plan-f1-lakehouse
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.3
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -no-color
